# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-server
    privileged: true
    hostname: jenkinsserver
    user: root
    labels:
      com.example.description: "Jenkins-Server by DigitalAvenue.dev"
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    ports: 
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    networks:
      dev:
        ipv4_address: 10.5.0.2
    volumes: 
      - ./entrypoint.sh:/entrypoint.sh 
      - ./html.tpl:/html.tpl 
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash entrypoint.sh

  sonarqube:
    image: sonarqube
    container_name: sonarqube-server
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:  
      dev:
        ipv4_address: 10.5.0.3
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    container_name: postgres-sonarqube
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    networks:
      dev:
        ipv4_address: 10.5.0.4
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data 

  nexus:
    image: sonatype/nexus3
    container_name: nexus3-server
    restart: always
    ports: 
      - 8088:8081
      - 8000:8000
    networks:   
      dev:
        ipv4_address: 10.5.0.5
    volumes:
      - nexus3_data:/nexus-data

  scope:
    image: weaveworks/scope:1.13.2
    container_name: weavescope
    restart: unless-stopped
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
      - "--weave=false"
    ports:
      - "4040:4040"
    networks:
      dev:
        ipv4_address: 10.5.0.6
     
volumes: 
  jenkins-data:
    name: jenkins-data
  postgresql_data:
    name: postgresql_data
  sonarqube_bundled-plugins:
    name: sonarqube_bundled-plugins
  sonarqube_conf:
    name: sonarqube_conf
  sonarqube_data:
    name: sonarqube_data
  sonarqube_db:
    name: sonarqube_db
  sonarqube_extensions:
    name: sonarqube_extensions
  nexus3_data:
    name: nexus3_data

networks:
  dev:
    name: dev
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1  